services:
  app:
    build: .
    container_name: market_scrapper_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - market_scrapper_network
    command: python app/main.py

  db:
    image: postgres:13
    container_name: market_scrapper_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market_scrapper_network

networks:
  market_scrapper_network:
    driver: bridge

volumes:
  postgres_data:
